version: '3'
services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    command: go run .
    environment:
      MYSQL_URI: 'root:root@tcp(db:3306)/tmitter?multiStatements=true'
      APP_PORT: '8080'
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'tmitter'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - sql-db:/var/lib/mysql
volumes:
  sql-db:
